<a href="https://colab.research.google.com/github/CoderTuran/Pyhton-Veri-Analizi/blob/main/Python_Veri_Analizi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas
import numpy as np
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import seaborn as sns

In [42]:
df=sns.load_dataset("titanic")

In [43]:
df2.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [48]:
#pd.crosstab(df["sex"],df["alive"])
pd.crosstab(df.sex,df.alive)

alive    no  yes
sex
female   81  233
male    468  109

In [54]:
df.groupby("sex").agg({"survived":"mean"})

        survived
sex
female  0.742038
male    0.188908

In [58]:
df.groupby(["sex","pclass"]).agg({"survived":["count","mean"]})

              survived
                 count      mean
sex    pclass
female 1            94  0.968085
       2            76  0.921053
       3           144  0.500000
male   1           122  0.368852
       2           108  0.157407
       3           347  0.135447

In [59]:
df["fare"]<30  #

0       True
1      False
2       True
3      False
4       True
       ...
886     True
887    False
888     True
889    False
890     True
Name: fare, Length: 891, dtype: bool

In [60]:
df.isnull().sum()  #missing value bulduk

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [65]:
#177 adet veri kayıp ama % kaça denk gelıyor(datayı toplam gözlem sayısına böleriz oda shape [0])
df.shape

(891, 15)

In [66]:
df.isnull().sum()/df.shape[0]         #kayıp verilerin toplam dataya oranı

survived       0.000000
pclass         0.000000
sex            0.000000
age            0.198653
sibsp          0.000000
parch          0.000000
fare           0.000000
embarked       0.002245
class          0.000000
who            0.000000
adult_male     0.000000
deck           0.772166
embark_town    0.002245
alive          0.000000
alone          0.000000
dtype: float64

In [68]:
df["age"].sum()

21205.17

In [69]:
df["age"].count()

714

In [70]:
df["age"].mean()

29.69911764705882

In [73]:
df["embark_town"].value_counts()/df.shape[0] #embarkın % sel dağılımını getirdik

embark_town
Southampton    0.722783
Cherbourg      0.188552
Queenstown     0.086420
Name: count, dtype: float64

In [83]:

kolonlar=["embark_town","sex","class","who"]  #Kolonlarım dolaşarak % lerini otomatize şekilde buldum
for col in kolonlar:
  print(df[col].value_counts()/df.shape[0])
  print(".......")

embark_town
Southampton    0.722783
Cherbourg      0.188552
Queenstown     0.086420
Name: count, dtype: float64
.......
sex
male      0.647587
female    0.352413
Name: count, dtype: float64
.......
class
Third     0.551066
First     0.242424
Second    0.206510
Name: count, dtype: float64
.......
who
man      0.602694
woman    0.304153
child    0.093154
Name: count, dtype: float64
.......

In [86]:
df.dtypes #dataframde veri tiplerine bakmak.

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [87]:
df.columns  #colonları array biçimde listeler

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [103]:
#kolonların tipine gördükten sonra ister for döngüsü ile ister manuel şekilde kategorik ve numeric olarak 2 ye ayırdık
#bunu yapmamızın nedeni 2 veritipindede farklı işlemler gerçekleştiricez.
num_columns=['survived', 'age','sibsp','parch','fare','alive','alone']
cat_columns=[ 'pclass', 'sex', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', ]

In [104]:
num_columns

['survived', 'age', 'sibsp', 'parch', 'fare', 'alive', 'alone']

In [105]:
cat_columns

['pclass',
 'sex',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive']

In [108]:
df[num_columns] #dersem dataframe şeklinde numeric kolonlarımın tablosunu getirir.

     survived   age  sibsp  parch     fare alive  alone
0           0  22.0      1      0   7.2500    no  False
1           1  38.0      1      0  71.2833   yes  False
2           1  26.0      0      0   7.9250   yes   True
3           1  35.0      1      0  53.1000   yes  False
4           0  35.0      0      0   8.0500    no   True
..        ...   ...    ...    ...      ...   ...    ...
886         0  27.0      0      0  13.0000    no   True
887         1  19.0      0      0  30.0000   yes   True
888         0   NaN      1      2  23.4500    no  False
889         1  26.0      0      0  30.0000   yes   True
890         0  32.0      0      0   7.7500    no   True

[891 rows x 7 columns]

In [109]:
df[num_columns].columns  #bu şekilde sadece array şeklinde getirir.

Index(['survived', 'age', 'sibsp', 'parch', 'fare', 'alive', 'alone'], dtype='object')